#ifndef CAN_COMMON_H
#define CAN_COMMON_H

#include <Arduino.h>

/**
 * Generic struct representing a CAN message.
 * Should be generated by a HAL in the future
 */
struct canmsg_t {
    uint32_t address;
    size_t size;
    uint8_t data[8];

    operator bool() { return address || size; }
};

#endif